apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "spring-boot-app.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "spring-boot-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}