apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "endpoints"]
    verbs: [ "get", "list", "watch"]
  - apiGroups: [ "extensions" ]
    resources: [ "deployments", "endpoints" ]
    verbs: [ "get", "list", "watch"]