{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spring-boot-app.serviceAccountName" . }}
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
{{- end -}}