management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: "logs.txt"

app:
  spring:
    boot:
      version: "@project.version@"