name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: 'maven'

      - name: Build Spring Boot Apps
        run: mvn -B clean install
